#!/usr/bin/env python3
from libtrx.cli.sort_imports import run_script
from tr2x.paths import TR2X_REPO_DIR, TR2X_SRC_DIR

run_script(
    root_dir=TR2X_SRC_DIR,
    include_dirs=[
        TR2X_SRC_DIR,
        TR2X_REPO_DIR / "build/linux",
        TR2X_REPO_DIR / "build/windows",
    ],
    system_include_dirs=[TR2X_REPO_DIR / "subprojects/libtrx/include"],
    own_include_map={
        "game/music/music_main.c": "game/music.h",
    },
    fix_map={},
    forced_order=["<ddrawi.h>", "<d3dhal.h>"],
)
